/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'perryw' at '2/13/18 7:12 PM' with Gradle 2.10
 *
 * @author perryw, @date 2/13/18 7:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
