import org.junit.Test;

import static junit.framework.Assert.assertTrue;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'perryw' at '2/13/18 7:12 PM' with Gradle 2.10
 *
 * @author perryw, @date 2/13/18 7:12 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
